Refactored USDC component to use redux store instead of useState
wormhole-foundation/example-token-bridge-ui pull request #35
Opened 2022-11-29 21:31 UTC by kev1n-peters

Resolves #34

2022-11-29 21:33 UTC, kev1n-peters commented on src/components/USDC/index.tsx
> +      dispatch(setMaxSwapAmount(maxSwap.toString()));
redux can't handle the `bigint` type, because it's non-serializable, so we store as a string instead

2022-12-01 15:24 UTC, evan-gray commented
Encountering this issue when using the relayer and moving to the redeem step.
```
Uncaught (in promise) Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="decimals()"
Uncaught (in promise) Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="relayerFee(uint16,address)"
```

2022-12-01 15:33 UTC, evan-gray requested changes
(see comment)

2022-12-01 18:43 UTC, evan-gray approved these changes
did a few transfers and seems to work. not sure what causes the bad `decimals` call (likely a bad effect) but it seems like it might have been there before.

2022-12-01 19:33 UTC, merged